export * from './login'
export * from './sample'
export * from './products'
export * from './subCategory'
export * from './newArrivals'
export * from './bestSelling'
export * from './web'
export * from './banners'
export * from './testimonial'
// export * from './samples'
